### ISSUE TITLE
Change the metodología content to with the content of the metodología doc attached

### ISSUE THREAD

**Issue by RaymondBalise** [RaymondBalise/Covid19Americas#41]
Email On May 9, 2020, at 12:51 PM, Thalia Porteny Re: Updates for webpage
[Metodología_updated.docx](https://github.com/RaymondBalise/Covid19Americas/files/4606645/Metodologia_updated.docx)

**Comment by miketouchton** [comment]
Can you please also fix the typo in the metodologia text? the sixth paragraph still has this: "que toma valores de 0 a 1003" 

It should be "100" not "1003". thanks!!!
