### ISSUE TITLE
Review state names 

### ISSUE THREAD

**Issue by RaymondBalise** [RaymondBalise/Covid19Americas#44]
Review the state names? Including the accents. And make sure it is “estado de Mexico”.

**Comment by miketouchton** [comment]
Did anyone get to this? It should be Estado de México (accent on the "e" in Mexico). Same with Ciudad de México (accent on the e in Mexico). 

Here are the other states with missing accents: 

Michoacán

Nuevo León

Querétaro

San Luis Potosí

Yucatán

**Comment by labouz** [comment]
done.
