### ISSUE TITLE
New data ready for update

### ISSUE THREAD

**Issue by miketouchton** [RaymondBalise/Covid19Americas#53]
Hi Layla and Ray, 

we're ready to update through May 7. Please use : COVID-19 mayo 15 y movilidad google al 7 de mayo.dta     (in the dropbox data updates folder). 

The new policy index variable is: Policy_Index_Adjusted_Time. The mobility variable is Mobility_Index. 

The other variables are the same.

**Comment by RaymondBalise** [comment]
The name of the variable is `Policy Index Adjusted for Time` not Policy_Index_Adjusted_Time.

**Comment by RaymondBalise** [comment]
The International Travel Restriction variable is bugged.
